dist: cosmic
sudo: required
language:
  - cpp
compiler:
  - gcc
before_install:
  - sudo add-apt-repository main -y
  - sudo add-apt-repository "deb http://us-east-1.ec2.archive.ubuntu.com/ubuntu cosmic main universe restricted multiverse InRelease" -y
  - sudo add-apt-repository restricted -y
  - sudo add-apt-repository multiverse -y
  - sudo apt-get update -q
  - sudo apt-get install -y libpmemblk-dev libtbb-dev
addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake
script:
  - sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++
  - export CC=/usr/local/bin/gcc
  - export CXX=/usr/local/bin/g++
  - /usr/local/bin/gcc -v && /usr/local/bin/g++ -v && cmake --version
  - mkdir build
  - cd build
  - cmake ..
  - make