dist: cosmic

sudo: required

language:
  - cpp

install: sudo apt-get install gcc-8 g++-8
compiler: gcc

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"



addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - g++-8

before_install:
  - eval "${MATRIX_EVAL}"
  - sudo add-apt-repository main -y
  - sudo add-apt-repository "deb http://us-east-1.ec2.archive.ubuntu.com/ubuntu cosmic main universe restricted multiverse InRelease" -y
  - sudo add-apt-repository restricted -y
  - sudo add-apt-repository multiverse -y
  - sudo apt-get update -q
  - sudo apt-get install -y libpmemblk-dev libtbb-dev

script:
  - gcc-8 -v && g++-8 -v && cmake --version
  - mkdir build
  - cd build
  - cmake ..
  - make