os: linux
dist: xenial
sudo: false
language: cpp
compiler: gcc
addons:
  apt:
    update: true
    sources:
      - sourceline: "deb http://us-east-1.ec2.archive.ubuntu.com/ubuntu cosmic main universe InRelease"
      - ubuntu-toolchain-r-test
    packages:
      - libboost-all-dev
      - doxygen
      - libpmemblk-dev
      - libtbb-dev
cache:
  apt: true

script:
  - mkdir build
  - cd build
  - cmake ..
  - make

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build/documentation/html
  github_token: 4d426cebc8fdff2cac32b93033e87698ac59b948
  on:
    branch: master

