os: linux
dist: xenial
sudo: false
language: cpp
compiler: gcc
addons:
  apt:
    update: true
    sources:
      - sourceline: "deb http://us-east-1.ec2.archive.ubuntu.com/ubuntu cosmic main universe InRelease"
      - ubuntu-toolchain-r-test
    packages:
      - libboost-program-options-dev
      - libboost-filesystem-dev
      - doxygen
      - libpmemblk-dev
      - libtbb-dev
      - virtualenv
      - python3-sphinx
      - zip
cache:
  apt: true
  pip: true

script:
  - virtualenv -p $(which python3) py3env
  - source py3env/bin/activate
  - pip install breathe exhale m2r guzzle_sphinx_theme sphinx-jekyll-builder
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ls
  - zip -r BLKCACHED-$(echo $RELEASE_VERSION).zip bin

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build/docs/sphinx
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master

#deploy:
#  provider: releases
#  api_key: $GITHUB_TOKEN
#  file: build/BLKCACHED-$RELEASE_VERSION.zip
#  keep_history: true
#  skip_cleanup: true
#  draft: true
