dist: cosmic

sudo: required

language:
  - cpp

compiler: gcc

before_install:
  - eval "${MATRIX_EVAL}"
  - sudo add-apt-repository "deb http://us-east-1.ec2.archive.ubuntu.com/ubuntu cosmic main universe InRelease" -y
  - sudo apt-get update -q
  - sudo apt-get install -y libpmemblk-dev libtbb-dev libboost-all-dev doxygen

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
after_success:
  - >-
    if [[ "$TRAVIS_BRANCH" = "master"]] ; then
      cd $PROJECT_DIR_ABS
      ls .ci
      .ci/push_docs.sh || travis_terminate 1
    fi